[project]
name = "django-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "gunicorn>=23.0.0",
    "markdown>=3.8.2",
    "python-dotenv>=1.1.1",
]
